import type { Metadata } from "next";
import { Inter, Roboto, Poppins, Montserrat } from "next/font/google";
import classNames from "classnames";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: ['300', '400', '700'], subsets: ["latin"] });
const monseart = Montserrat({ weight: ['300', '400', '700'], subsets: ["latin"] });
const popins = Poppins({ weight: ['400', '700'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          className={classNames(inter.className)}
      >
        {children}
      </body>
    </html>
  );
}
